// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00VgWm0hNRQh9N_jDpeqwDFNZoLsIfj8',
    appId: '1:767097936113:ios:f3d1b9c7c39c8090b7b150',
    messagingSenderId: '767097936113',
    projectId: 'follow-up-tool-7f866',
    storageBucket: 'follow-up-tool-7f866.firebasestorage.app',
    iosBundleId: 'com.example.sendMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLJZoFV2NWVgX4HesNlo1oJE7jJ1zOpAA',
    appId: '1:767097936113:web:1991c08ea23aca3ab7b150',
    messagingSenderId: '767097936113',
    projectId: 'follow-up-tool-7f866',
    authDomain: 'follow-up-tool-7f866.firebaseapp.com',
    storageBucket: 'follow-up-tool-7f866.firebasestorage.app',
    measurementId: 'G-GX81QRQRG8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00VgWm0hNRQh9N_jDpeqwDFNZoLsIfj8',
    appId: '1:767097936113:ios:f3d1b9c7c39c8090b7b150',
    messagingSenderId: '767097936113',
    projectId: 'follow-up-tool-7f866',
    storageBucket: 'follow-up-tool-7f866.firebasestorage.app',
    iosBundleId: 'com.example.sendMessage',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotnAfTFY4MoodeIfmwNUX6IguM-ViSXc',
    appId: '1:767097936113:android:42050e69af5e4546b7b150',
    messagingSenderId: '767097936113',
    projectId: 'follow-up-tool-7f866',
    storageBucket: 'follow-up-tool-7f866.firebasestorage.app',
  );

}
